//! What this consumer can be asked to do.
//!
//! Declared here rather than generated by `#[lez_program]`, because a host-side
//! caller now exists: M3-07 drives this program across a standalone sequencer,
//! and a test in another workspace cannot reach a type the macro creates inside
//! the guest binary. `[M3-06:01]` records the change and what it costs.
//!
//! Serde and not Borsh, because serde is what the wire uses: the dispatcher
//! deserialises this with `risc0_zkvm::serde`, and **a variant's position in
//! this declaration is the discriminant a caller encodes**. That ordering is the
//! one thing the macro used to guarantee for free -- as is the order of the
//! fields inside a variant, which SPEL fills positionally -- so
//! `tests/instruction_parity.rs` asserts both against the committed IDL, which
//! `tests/idl.rs` in turn holds against the guest's own handlers.
//!
//! Each variant names the accounts its handler expects, in order, because a
//! caller has to supply them in that order. Why each one is required, and what
//! is checked about it, stays in the handler's own doc comment: this is the
//! surface, not a second copy of the reasoning.

use serde::{Deserialize, Serialize};

/// One instruction, in the order the guest declares its handlers.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Instruction {
    /// Claim the authority for a build that has one compiled in and nobody
    /// holding it.
    ///
    /// Accounts: `config`, `authority`.
    EstablishAuthority,

    /// Name a key that may take the authority over.
    ///
    /// Accounts: `config`, `authority`.
    NominateAuthority {
        /// The account id being nominated. Not the authority until it accepts.
        nominee: [u8; 32],
    },

    /// Take an authority that was nominated to this signer.
    ///
    /// Accounts: `config`, `nominee`.
    AcceptAuthority,

    /// Record what this consumer will believe for a feed.
    ///
    /// Accounts: `trust`, `authority`, `config`.
    RegisterFeedTrust {
        /// The RedStone data service the roster below came from.
        data_service_id: String,
        /// The RedStone feed id, right-padded to the wire's field width.
        feed_id: [u8; 32],
        /// The base asset of the pair this feed prices.
        base_asset: [u8; 32],
        /// The quote asset of the pair this feed prices.
        quote_asset: [u8; 32],
        /// The power of ten this feed's signers scale values by.
        decimals: u8,
        /// How old the oldest package behind a price may be.
        max_age_ms: u64,
        /// The authorised signers, in registration order.
        signers: Vec<[u8; 20]>,
        /// How many distinct authorised signers a price needs.
        threshold: u8,
    },

    /// Move a feed's roster and threshold together.
    ///
    /// Accounts: `trust`, `authority`, `config`.
    RotateSigners {
        /// The feed whose roster moves, named as well as addressed.
        feed_id: [u8; 32],
        /// The roster that replaces the stored one.
        signers: Vec<[u8; 20]>,
        /// The threshold that replaces the stored one.
        threshold: u8,
    },

    /// Retire a feed, leaving its account empty and still this program's.
    ///
    /// Accounts: `trust`, `authority`, `config`.
    DeregisterFeedTrust {
        /// The feed being retired, named as well as addressed.
        feed_id: [u8; 32],
    },

    /// Record a price its owner is prepared to trade at.
    ///
    /// Accounts: `order`, `owner`, `trust`.
    OpenOrder {
        /// The id this order's address derives from. Spent once.
        order_id: [u8; 32],
        /// The feed the order is priced against.
        feed_id: [u8; 32],
        /// The base asset the owner is signing for, and not a copy of the
        /// registration's: the comparison is what makes a mislabelled feed
        /// catchable.
        base_asset: [u8; 32],
        /// The quote asset the owner is signing for.
        quote_asset: [u8; 32],
        /// The price, on RFP-019's `Q64.64` scale, at or above which it fills.
        limit_price_q64: u128,
    },

    /// Fill an order if a payload verified here says the market reached it.
    ///
    /// Accounts: `order`, `trust`, `clock`.
    Settle {
        /// The id the order's address derives from, and the whole reason the
        /// account offered as an order is the one `open_order` created.
        order_id: [u8; 32],
        /// The feed the payload is verified against.
        feed_id: [u8; 32],
        /// The payload as RedStone serialises it, packages and envelope.
        payload: Vec<u8>,
    },
}
