//! Guest ELFs and image IDs for the product guests.
//!
//! Generated by `build.rs`: one `<NAME>_ELF` and one `<NAME>_ID` per binary
//! under `guest/src/bin`.
include!(concat!(env!("OUT_DIR"), "/methods.rs"));

/// How the guests above were compiled: `container` or `host`.
///
/// A host build's image ids depend on the absolute path this repository was checked out
/// at, so they are not the ids anybody else's build produces and must not be published
/// (`[M3-08:02]`). This is what lets a test say so rather than a build warning nobody
/// reads.
pub const GUEST_BUILD_MODE: &str = env!("KANON_GUEST_BUILD_MODE");
