//! Guest ELFs and image IDs for the product guests.
//!
//! Generated by `build.rs`: one `<NAME>_ELF` and one `<NAME>_ID` per binary
//! under `guest/src/bin`.
include!(concat!(env!("OUT_DIR"), "/methods.rs"));
