[package]
name = "lez-probe"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
risc0-zkvm.workspace = true
lez-probe-methods-mixed = { path = "../methods-mixed" }
lez-probe-methods-accelerated = { path = "../methods-accelerated" }
lee_core = { git = "https://github.com/logos-blockchain/logos-execution-zone", rev = "15144ddb8437f48cdce32908e122dbb7eea68399", features = ["host"] }
anyhow = "1"
serde = "1"
borsh = "1"
clap = { version = "4", features = ["derive"] }
k256.workspace = true
tiny-keccak.workspace = true
